<?php

declare(strict_types=1);

namespace App\Support;

final class Countries
{
    public static function all(): array
    {
        return [
            'aa' => 'Mondo',
            'ad' => 'Andorra',
            'ae' => 'Emirati Arabi Uniti',
            'af' => 'Afghanistan',
            'ag' => 'Antigua e Barbuda',
            'ai' => 'Anguilla',
            'al' => 'Albania',
            'am' => 'Armenia',
            'ao' => 'Angola',
            'aq' => 'Antartide',
            'ar' => 'Argentina',
            'as' => 'Samoa Americane',
            'at' => 'Austria',
            'au' => 'Australia',
            'aw' => 'Aruba',
            'ax' => 'Isole Åland',
            'az' => 'Azerbaigian',
            'ba' => 'Bosnia ed Erzegovina',
            'bb' => 'Barbados',
            'bd' => 'Bangladesh',
            'be' => 'Belgio',
            'bf' => 'Burkina Faso',
            'bg' => 'Bulgaria',
            'bh' => 'Bahrein',
            'bi' => 'Burundi',
            'bj' => 'Benin',
            'bl' => 'Saint-Barthélemy',
            'bm' => 'Bermuda',
            'bn' => 'Brunei',
            'bo' => 'Bolivia',
            'bq' => 'Paesi Bassi caraibici',
            'br' => 'Brasile',
            'bs' => 'Bahamas',
            'bt' => 'Bhutan',
            'bv' => 'Isola Bouvet',
            'bw' => 'Botswana',
            'by' => 'Bielorussia',
            'bz' => 'Belize',
            'ca' => 'Canada',
            'cc' => 'Isole Cocos (Keeling)',
            'cd' => 'Congo (RD)',
            'cf' => 'Repubblica Centrafricana',
            'cg' => 'Repubblica del Congo',
            'ch' => 'Svizzera',
            'ci' => "Costa d'Avorio",
            'ck' => 'Isole Cook',
            'cl' => 'Cile',
            'cm' => 'Camerun',
            'cn' => 'Cina',
            'co' => 'Colombia',
            'cr' => 'Costa Rica',
            'cu' => 'Cuba',
            'cv' => 'Capo Verde',
            'cw' => 'Curaçao',
            'cx' => 'Isola di Natale',
            'cy' => 'Cipro',
            'cz' => 'Cechia',
            'de' => 'Germania',
            'dj' => 'Gibuti',
            'dk' => 'Danimarca',
            'dm' => 'Dominica',
            'do' => 'Repubblica Dominicana',
            'dz' => 'Algeria',
            'ec' => 'Ecuador',
            'ee' => 'Estonia',
            'eg' => 'Egitto',
            'eh' => 'Sahara Occidentale',
            'er' => 'Eritrea',
            'es' => 'Spagna',
            'et' => 'Etiopia',
            'eu' => 'Unione Europea',
            'fi' => 'Finlandia',
            'fj' => 'Figi',
            'fk' => 'Isole Falkland',
            'fm' => 'Micronesia',
            'fo' => 'Isole Fær Øer',
            'fr' => 'Francia',
            'ga' => 'Gabon',
            'gb' => 'Regno Unito',
            'gb-eng' => 'Inghilterra',
            'gb-nir' => 'Irlanda del Nord',
            'gb-sct' => 'Scozia',
            'gb-wls' => 'Galles',
            'gd' => 'Grenada',
            'ge' => 'Georgia',
            'gf' => 'Guyana Francese',
            'gg' => 'Guernsey',
            'gh' => 'Ghana',
            'gi' => 'Gibilterra',
            'gl' => 'Groenlandia',
            'gm' => 'Gambia',
            'gn' => 'Guinea',
            'gp' => 'Guadalupa',
            'gq' => 'Guinea Equatoriale',
            'gr' => 'Grecia',
            'gs' => 'Georgia del Sud',
            'gt' => 'Guatemala',
            'gu' => 'Guam',
            'gw' => 'Guinea-Bissau',
            'gy' => 'Guyana',
            'hk' => 'Hong Kong',
            'hn' => 'Honduras',
            'hr' => 'Croazia',
            'ht' => 'Haiti',
            'hu' => 'Ungheria',
            'id' => 'Indonesia',
            'ie' => 'Irlanda',
            'il' => 'Israele',
            'im' => 'Isola di Man',
            'in' => 'India',
            'io' => "Territorio Britannico dell'Oceano Indiano",
            'iq' => 'Iraq',
            'ir' => 'Iran',
            'is' => 'Islanda',
            'it' => 'Italia',
            'jm' => 'Giamaica',
            'jo' => 'Giordania',
            'jp' => 'Giappone',
            'ke' => 'Kenya',
            'kr' => 'Corea del Sud',
            'ma' => 'Marocco',
            'mx' => 'Messico',
            'ng' => 'Nigeria',
            'nl' => 'Paesi Bassi',
            'no' => 'Norvegia',
            'pl' => 'Polonia',
            'pt' => 'Portogallo',
            'ro' => 'Romania',
            'rs' => 'Serbia',
            'ru' => 'Russia',
            'sa' => 'Arabia Saudita',
            'se' => 'Svezia',
            'si' => 'Slovenia',
            'sk' => 'Slovacchia',
            'sn' => 'Senegal',
            'tn' => 'Tunisia',
            'tr' => 'Turchia',
            'ua' => 'Ucraina',
            'us' => 'Stati Uniti',
            'uy' => 'Uruguay',
            've' => 'Venezuela',
            'za' => 'Sudafrica',
            'zw' => 'Zimbabwe',
        ];
    }

    public static function nameFromCode(?string $code): ?string
    {
        if ($code === null || $code === '') {
            return null;
        }

        $countries = self::all();

        return $countries[$code] ?? null;
    }
}