<?php

namespace App\Support;

final class Names
{
    public static function firstNames(): array
    {
        return [
            'Aaron',
            'Abramo',
            'Achille',
            'Adalberto',
            'Adamo',
            'Adriano',
            'Agostino',
            'Aldo',
            'Alessandro',
            'Alessio',
            'Alfio',
            'Alfonso',
            'Alvise',
            'Amedeo',
            'Amos',
            'Andrea',
            'Angelo',
            'Anselmo',
            'Antonio',
            'Aristide',
            'Armando',
            'Arnaldo',
            'Arturo',
            'Attilio',
            'Augusto',
            'Aurelio',
            'Aureliano',
            'Aurelio',
            'Baldassarre',
            'Bartolomeo',
            'Basilio',
            'Benito',
            'Benedetto',
            'Beniamino',
            'Bernardo',
            'Biagio',
            'Bruno',
            'Calogero',
            'Camillo',
            'Carlo',
            'Carmelo',
            'Carmine',
            'Casimiro',
            'Celestino',
            'Cesare',
            'Christian',
            'Cristian',
            'Cristiano',
            'Ciro',
            'Claudio',
            'Clemente',
            'Corrado',
            'Cosimo',
            'Costantino',
            'Damiano',
            'Daniele',
            'Danilo',
            'Dante',
            'Dario',
            'Davide',
            'Diego',
            'Dino',
            'Domenico',
            'Edoardo',
            'Edmondo',
            'Egidio',
            'Elia',
            'Elio',
            'Emanuele',
            'Emiliano',
            'Emilio',
            'Ennio',
            'Enrico',
            'Ercole',
            'Ermanno',
            'Ernesto',
            'Ettore',
            'Eugenio',
            'Ezio',
            'Fabiano',
            'Fabio',
            'Fausto',
            'Federico',
            'Felice',
            'Feliciano',
            'Ferdinando',
            'Fernando',
            'Filiberto',
            'Filippo',
            'Flavio',
            'Fortunato',
            'Francesco',
            'Franco',
            'Fulvio',
            'Gabriele',
            'Gaetano',
            'Gastone',
            'Gennaro',
            'Gerardo',
            'Germano',
            'Giacinto',
            'Giacomo',
            'Gian',
            'Gianfranco',
            'Gianluca',
            'Gianmarco',
            'Gianni',
            'Gilberto',
            'Gino',
            'Giorgio',
            'Giovanni',
            'Giulio',
            'Giuseppe',
            'Gregorio',
            'Guido',
            'Iacopo',
            'Ignazio',
            'Ilario',
            'Ivan',
            'Jacopo',
            'Jonathan',
            'Kevin',
            'Lamberto',
            'Lanfranco',
            'Lazzaro',
            'Leandro',
            'Leone',
            'Leonardo',
            'Leopoldo',
            'Lino',
            'Livio',
            'Lorenzo',
            'Loris',
            'Luca',
            'Luciano',
            'Lucio',
            'Luigi',
            'Manfredi',
            'Manlio',
            'Manuel',
            'Marcello',
            'Marco',
            'Mariano',
            'Mario',
            'Martino',
            'Massimiliano',
            'Massimo',
            'Matteo',
            'Mattia',
            'Maurizio',
            'Michele',
            'Mirco',
            'Mirko',
            'Moreno',
            'Nazzareno',
            'Nereo',
            'Niccolò',
            'Nicola',
            'Nicolò',
            'Nino',
            'Noè',
            'Norberto',
            'Omar',
            'Orazio',
            'Orfeo',
            'Orlando',
            'Oscar',
            'Ottavio',
            'Pacifico',
            'Paolo',
            'Pasquale',
            'Patrizio',
            'Piero',
            'Pierluigi',
            'Pierpaolo',
            'Pietro',
            'Primo',
            'Quirino',
            'Raffaele',
            'Raul',
            'Remo',
            'Renato',
            'Riccardo',
            'Rinaldo',
            'Roberto',
            'Rodolfo',
            'Romano',
            'Romeo',
            'Ruggero',
            'Salvatore',
            'Samuele',
            'Sandro',
            'Saverio',
            'Sebastiano',
            'Secondo',
            'Sergio',
            'Silvano',
            'Silvio',
            'Simone',
            'Stefano',
            'Tarcisio',
            'Teodoro',
            'Terenzio',
            'Tiziano',
            'Tobia',
            'Tommaso',
            'Tullio',
            'Ubaldo',
            'Ugo',
            'Umberto',
            'Valentino',
            'Valerio',
            'Vasco',
            'Venanzio',
            'Vincenzo',
            'Virginio',
            'Vito',
            'Walter',
            'William',
            'Yuri',
            'Zaccaria',
            'Zeno',

            // Varianti e nomi internazionali
            'Adam',
            'Adrian',
            'Alan',
            'Albert',
            'Alberto',
            'Alec',
            'Alex',
            'Alexander',
            'Alfredo',
            'Alvin',
            'Andrew',
            'Anthony',
            'Arthur',
            'Austin',
            'Benjamin',
            'Blake',
            'Brandon',
            'Brian',
            'Bruce',
            'Bryan',
            'Caleb',
            'Carl',
            'Carlos',
            'Cedric',
            'Charles',
            'Chris',
            'Christopher',
            'Clarence',
            'Cole',
            'Colin',
            'Connor',
            'Damien',
            'Daniel',
            'Darren',
            'Dean',
            'Dennis',
            'Derek',
            'Dominic',
            'Donald',
            'Douglas',
            'Dylan',
            'Edward',
            'Edwin',
            'Elias',
            'Elijah',
            'Elliot',
            'Ellis',
            'Eric',
            'Erik',
            'Ethan',
            'Evan',
            'Felix',
            'Finn',
            'Francis',
            'Frank',
            'Gabriel',
            'Gareth',
            'Gary',
            'Gavin',
            'George',
            'Gerald',
            'Gordon',
            'Graham',
            'Grant',
            'Harold',
            'Harry',
            'Henry',
            'Howard',
            'Hugo',
            'Ian',
            'Isaac',
            'Isaiah',
            'Jack',
            'Jackson',
            'Jacob',
            'James',
            'Jamie',
            'Jason',
            'Jay',
            'Jeff',
            'Jeffrey',
            'Jeremy',
            'Jerry',
            'Jesse',
            'Jim',
            'Jimmy',
            'Joel',
            'John',
            'Johnny',
            'Jon',
            'Jordan',
            'Joseph',
            'Joshua',
            'Julian',
            'Justin',
            'Keith',
            'Kenneth',
            'Kyle',
            'Lance',
            'Larry',
            'Lawrence',
            'Leo',
            'Leon',
            'Leonard',
            'Lewis',
            'Liam',
            'Logan',
            'Louis',
            'Lucas',
            'Luis',
            'Malcolm',
            'Marcus',
            'Mark',
            'Martin',
            'Mason',
            'Matthew',
            'Max',
            'Michael',
            'Miles',
            'Morgan',
            'Nathan',
            'Nathaniel',
            'Neil',
            'Nicholas',
            'Noah',
            'Norman',
            'Oliver',
            'Owen',
            'Patrick',
            'Paul',
            'Peter',
            'Philip',
            'Quentin',
            'Ralph',
            'Randall',
            'Raymond',
            'Richard',
            'Robert',
            'Roger',
            'Roland',
            'Ronald',
            'Ross',
            'Roy',
            'Ryan',
            'Samuel',
            'Scott',
            'Sean',
            'Sebastian',
            'Shawn',
            'Simon',
            'Spencer',
            'Stanley',
            'Stephen',
            'Steve',
            'Steven',
            'Stuart',
            'Taylor',
            'Terence',
            'Terrence',
            'Terry',
            'Theodore',
            'Thomas',
            'Tim',
            'Timothy',
            'Todd',
            'Tony',
            'Travis',
            'Trevor',
            'Tyler',
            'Victor',
            'Vincent',
            'Wade',
            'Warren',
            'Wayne',
            'Wesley',
            'Will',
            'William',
            'Zachary',

            // Altri
            'Abel',
            'Aidan',
            'Aitor',
            'Albertino',
            'Albin',
            'Aldric',
            'Alessandrino',
            'Alessandrone',
            'Almerico',
            'Amilcare',
            'Anatolio',
            'Anatolio',
            'Anatolio',
            'Aniceto',
            'Annibale',
            'Apollo',
            'Araldo',
            'Armando',
            'Arnaldo',
            'Aronne',
            'Ascanio',
            'Astolfo',
            'Atanasio',
            'Atilio',
            'Beniamino',
            'Bonaventura',
            'Callisto',
            'Candido',
            'Casimiro',
            'Celso',
            'Cesario',
            'Cirillo',
            'Cornelio',
            'Decimo',
            'Demetrio',
            'Desiderio',
            'Duilio',
            'Edgardo',
            'Edmond',
            'Efisio',
            'Enea',
            'Enzo',
            'Erasmo',
            'Ermes',
            'Fabrizio',
            'Fedele',
            'Fiorenzo',
            'Gaston',
            'Genesio',
            'Gervasio',
            'Giacobbe',
            'Giosuè',
            'Glauco',
            'Goffredo',
            'Graziano',
            'Ivo',
            'Lauro',
            'Lelio',
            'Libero',
            'Lionello',
            'Lodovico',
            'Loris',
            'Lucano',
            'Marzio',
            'Melchiorre',
            'Narciso',
            'Nazario',
            'Nestore',
            'Nevio',
            'Oliviero',
            'Onofrio',
            'Orfeo',
            'Osvaldo',
            'Palmiro',
            'Paride',
            'Pericle',
            'Pompeo',
            'Prospero',
            'Raimondo',
            'Raniero',
            'Renzo',
            'Rocco',
            'Romolo',
            'Ruben',
            'Rufino',
            'Sabatino',
            'Santino',
            'Saturnino',
            'Siro',
            'Tancredi',
            'Temistocle',
            'Tito',
            'Torquato',
            'Ulisse',
            'Valeriano',
            'Venceslao',
            'Zaccaria',
            'Zenobio'
        ];
    }

    public static function lastNames(): array
    {
        return [
            'Rossi',
            'Russo',
            'Ferrari',
            'Esposito',
            'Bianchi',
            'Romano',
            'Colombo',
            'Ricci',
            'Marino',
            'Greco',
            'Bruno',
            'Gallo',
            'Conti',
            'De Luca',
            'Mancini',
            'Costa',
            'Giordano',
            'Rizzo',
            'Lombardi',
            'Moretti',
            'Barbieri',
            'Fontana',
            'Santoro',
            'Mariani',
            'Rinaldi',
            'Caruso',
            'Ferrara',
            'Galli',
            'Martini',
            'Leone',
            'Longo',
            'Gentile',
            'Martinelli',
            'Vitale',
            'Lombardo',
            'Serra',
            'Coppola',
            'De Santis',
            'D\'Angelo',
            'Marchetti',
            'Parisi',
            'Villa',
            'Conte',
            'Ferraro',
            'Ferri',
            'Fabbri',
            'Bianco',
            'Marini',
            'Grasso',
            'Valentini',
            'Messina',
            'Sala',
            'De Angelis',
            'Gatti',
            'Pellegrini',
            'Palumbo',
            'Sanna',
            'Farina',
            'Rizzi',
            'Monti',
            'Cattaneo',
            'Morelli',
            'Amato',
            'Silvestri',
            'Testa',
            'Grassi',
            'Pellegrino',
            'Carbone',
            'Giuliani',
            'Benedetti',
            'Barone',
            'Rossetti',
            'Caputo',
            'Montanari',
            'Guerra',
            'Palmieri',
            'Bernardi',
            'Martino',
            'Fiore',
            'De Rosa',
            'Ferretti',
            'Bellini',
            'Basile',
            'Bellucci',
            'Donati',
            'Piras',
            'Vitali',
            'Battaglia',
            'Sartori',
            'Neri',
            'Costantini',
            'Milani',
            'Pagano',
            'Ruggiero',
            'Sorrentino',
            'Orlando',
            'Damico',
            'Negri',
            'Ruggeri',
            'Sanna',
            'Riva',
            'Mazza',
            'Catalano',
            'Rosati',
            'Molinari',
            'Moro',
            'Bassi',
            'Locatelli',
            'Piras',
            'Rossetto',
            'Ferraro',
            'Nicolini',
            'Valente',
            'Bertolini',
            'Grimaldi',
            'Mancuso',
            'Santini',
            'Carli',
            'Cattani',
            'Marotta',
            'Villa',
            'Santoro',
            'Rizzi',
            'Bergamini',
            'Rosso',
            'Venturi',
            'Baldini',
            'Pagani',
            'Corti',
            'Gatti',
            'Bellandi',
            'Landi',
            'Cavalieri',
            'D\'Amico',
            'Lazzari',
            'Fusco',
            'Bernasconi',
            'Bertoni',
            'Landi',
            'Lazzaro',
            'Pini',
            'Silvestri',
            'Piazza',
            'Puglisi',
            'Berlusconi',
            'Bertolotti',
            'Borrelli',
            'Bassi',
            'Bonetti',
            'Bonfiglio',
            'Bonini',
            'Bordoni',
            'Borghesi',
            'Bosco',
            'Botti',
            'Brambilla',
            'Bruni',
            'Buscemi',
            'Caldarola',
            'Calabrese',
            'Calvi',
            'Camerini',
            'Campanella',
            'Campisi',
            'Canepa',
            'Canessa',
            'Cannavaro',
            'Capobianco',
            'Caprioli',
            'Caridi',
            'Carlini',
            'Carlucci',
            'Carnesecchi',
            'Carrara',
            'Casadei',
            'Casali',
            'Casella',
            'Casini',
            'Cassano',
            'Castagna',
            'Castellani',
            'Castelli',
            'Cataldi',
            'Cavalli',
            'Cecconi',
            'Celentano',
            'Cerasi',
            'Cerboni',
            'Cereda',
            'Cerutti',
            'Chiappini',
            'Chiesa',
            'Ciampi',
            'Cimino',
            'Cinque',
            'Cipriani',
            'Coccia',
            'Colleoni',
            'Comi',
            'Corona',
            'Corradi',
            'Corrado',
            'Corsi',
            'Cortese',
            'Cosentino',
            'Costabile',
            'Crivelli',
            'Curti',
            'D\'Onofrio',
            'Dal Monte',
            'Dallari',
            'Della Rocca',
            'De Carlo',
            'De Felice',
            'De Francesco',
            'De Gennaro',
            'De Giovanni',
            'De Martino',
            'De Matteis',
            'De Simone',
            'Di Bari',
            'Di Bella',
            'Di Benedetto',
            'Di Carlo',
            'Di Filippo',
            'Di Giacomo',
            'Di Leo',
            'Di Lorenzo',
            'Di Marco',
            'Di Matteo',
            'Di Michele',
            'Di Paolo',
            'Di Pietro',
            'Di Stefano',
            'Donadio',
            'Doria',
            'Durante',
            'Esposito',
            'Fabiani',
            'Falcone',
            'Falco',
            'Fanti',
            'Faraone',
            'Farinelli',
            'Favero',
            'Felici',
            'Ferrante',
            'Fiorentino',
            'Fiorini',
            'Fiorucci',
            'Fois',
            'Forte',
            'Fortunato',
            'Franchi',
            'Franco',
            'Franzoni',
            'Freda',
            'Gagliardi',
            'Galati',
            'Gambino',
            'Gandolfi',
            'Garofalo',
            'Gasparini',
            'Gatti',
            'Genovese',
            'Germani',
            'Ghidini',
            'Giacomini',
            'Giannini',
            'Gigli',
            'Giorgi',
            'Giulietti',
            'Gobbi',
            'Gori',
            'Graziani',
            'Guarnieri',
            'Guerrieri',
            'Guidi',
            'Lorusso',
            'Lupo',
            'Macrì',
            'Maffei',
            'Magri',
            'Maiorano',
            'Malagoli',
            'Manca',
            'Mandelli',
            'Manfredi',
            'Mantovani',
            'Manzi',
            'Marchese',
            'Marchi',
            'Marconi',
            'Maresca',
            'Marinelli',
            'Marra',
            'Marrone',
            'Martelli',
            'Masini',
            'Masi',
            'Mastrodonato',
            'Mastroianni',
            'Mattioli',
            'Mazzaferro',
            'Medici',
            'Melis',
            'Mele',
            'Merlo',
            'Messori',
            'Migliore',
            'Minelli',
            'Monaco',
            'Montagna',
            'Montella',
            'Montemurro',
            'Montesano',
            'Morandi',
            'Moreno',
            'Mori',
            'Morra',
            'Motta',
            'Napolitano',
            'Natale',
            'Nicolosi',
            'Nobile',
            'Oliva',
            'Orsini',
            'Pace',
            'Padovani',
            'Paganelli',
            'Palladino',
            'Palmisano',
            'Panebianco',
            'Paoletti',
            'Papa',
            'Parente',
            'Pasquali',
            'Pastore',
            'Pavone',
            'Pedretti',
            'Pepe',
            'Peretti',
            'Perna',
            'Perotti',
            'Pesce',
            'Petrone',
            'Piccinini',
            'Piccolo',
            'Pinna',
            'Pinto',
            'Pisani',
            'Pisano',
            'Pizzi',
            'Poli',
            'Polito',
            'Ponti',
            'Pozzi',
            'Prato',
            'Quaranta',
            'Ragusa',
            'Raimondi',
            'Ranieri',
            'Rea',
            'Reale',
            'Reina',
            'Renzi',
            'Riva',
            'Rocca',
            'Rocchi',
            'Roda',
            'Romiti',
            'Ronchi',
            'Rota',
            'Rotondo',
            'Ruggieri',
            'Sacchi',
            'Sala',
            'Salerno',
            'Salvi',
            'Salvini',
            'Sammartino',
            'Sansonetti',
            'Santi',
            'Saracino',
            'Sarti',
            'Scalise',
            'Scalia',
            'Scalzo',
            'Scaramuzza',
            'Scarpa',
            'Schiavone',
            'Scognamiglio',
            'Severi',
            'Signorelli',
            'Silvestri',
            'Simonetti',
            'Spada',
            'Spinelli',
            'Stella',
            'Strano',
            'Tarantino',
            'Tedeschi',
            'Tempesta',
            'Terranova',
            'Tirabassi',
            'Tomasi',
            'Tomaselli',
            'Tomasino',
            'Tonelli',
            'Torre',
            'Toselli',
            'Tosoni',
            'Trentini',
            'Trevisan',
            'Trevisani',
            'Tricarico',
            'Valentini',
            'Valeri',
            'Valle',
            'Vanni',
            'Ventresca',
            'Verdi',
            'Vergani',
            'Veronese',
            'Vescovi',
            'Viola',
            'Visconti',
            'Vitelli',
            'Volpe',
            'Zaccaria',
            'Zamboni',
            'Zanetti',
            'Zanini',
            'Zanni',
            'Zappalà',
            'Zecchini',
            'Zingaretti',
            'Zito',
            'Zocchi',
            'Zucchi',
            'Abate',
            'Accardi',
            'Agosti',
            'Albertini',
            'Alfieri',
            'Allegri',
            'Altieri',
            'Ambrosini',
            'Andreoli',
            'Angelini',
            'Anselmi',
            'Antonelli',
            'Antonini',
            'Arena',
            'Argentieri',
            'Armani',
            'Arrighi',
            'Avallone',
            'Azzolini',
            'Bagnoli',
            'Baldi',
            'Ballarin',
            'Bandini',
            'Baraldi',
            'Baroni',
            'Bartoli',
            'Bellucci',
            'Benassi',
            'Benetti',
            'Bergamaschi',
            'Bertini',
            'Bettini',
            'Bevere',
            'Bonaccorsi',
            'Bonanno',
            'Bonfanti',
            'Bonifazi',
            'Borghi',
            'Bortolotti',
            'Bresciani',
            'Bugatti',
            'Buratti',
            'Cabras',
            'Caccia',
            'Cappelli',
            'Capri',
            'Cardinale',
            'Carletti',
            'Casadei',
            'Caserta',
            'Casiraghi',
            'Cavallaro',
            'Ceccarelli',
            'Cecchetti',
            'Cecere',
            'Chirico',
            'Ciavarella',
            'Ciliberto',
            'Cipolla',
            'Colangelo',
            'Colombo',
            'Corbo',
            'Corrias',
            'Crisafulli',
            'D\'Andrea',
            'D\'Errico',
            'D\'Alessandro',
            'D\'Alessio',
            'D\'Urso',
            'De Bellis',
            'De Falco',
            'De Pascale',
            'De Vita',
            'Del Vecchio',
            'Di Rosa',
            'Ferri',
            'Fioretti',
            'Giannone',
            'Ginesi',
            'Lagana',
            'Laganà',
            'Lattanzi',
            'Leoni',
            'Lisi',
            'Maddaloni',
            'Malatesta',
            'Mancini',
            'Marasco',
            'Mercuri',
            'Minervini',
            'Montanaro',
            'Muratori',
            'Nardelli',
            'Nardini',
            'Nasti',
            'Pagliuca',
            'Peluso'
        ];
    }

    public static function teamNames(): array
    {
        return [
            'Atletico Ligure',
            'Real Marittimo',
            'Sporting Porto Nuovo',
            'Virtus Levante',
            'Dynamo Centro',
            'FC Aurora',
            'Unione Riviera',
            'Città Vecchia',
            'Stella Azzurra',
            'Borgo United',
            'Atletico Aurora',
            'Real Aurora',
            'Virtus Aurora',
            'Sporting Aurora',
            'FC Aurora 2000',
            'AC Aurora',
            'Polisportiva Aurora',
            'US Aurora',
            'Aurora Calcio',
            'Aurora United',

            'Atletico Riviera',
            'Real Riviera',
            'Virtus Riviera',
            'Sporting Riviera',
            'FC Riviera',
            'AC Riviera',
            'Polisportiva Riviera',
            'US Riviera',
            'Riviera Calcio',
            'Riviera United',

            'Atletico Collina',
            'Real Collina',
            'Virtus Collina',
            'Sporting Collina',
            'FC Collina',
            'AC Collina',
            'Collina Calcio',
            'Collina United',
            'Polisportiva Collina',
            'US Collina',

            'Atletico Pianura',
            'Real Pianura',
            'Virtus Pianura',
            'Sporting Pianura',
            'FC Pianura',
            'AC Pianura',
            'Pianura Calcio',
            'Pianura United',
            'Polisportiva Pianura',
            'US Pianura',

            'Atletico San Marco',
            'Real San Marco',
            'Virtus San Marco',
            'Sporting San Marco',
            'FC San Marco',
            'AC San Marco',
            'San Marco Calcio',
            'San Marco United',
            'Polisportiva San Marco',
            'US San Marco',

            'Atletico San Giorgio',
            'Real San Giorgio',
            'Virtus San Giorgio',
            'Sporting San Giorgio',
            'FC San Giorgio',
            'AC San Giorgio',
            'San Giorgio Calcio',
            'San Giorgio United',
            'Polisportiva San Giorgio',
            'US San Giorgio',

            'Atletico Valverde',
            'Real Valverde',
            'Virtus Valverde',
            'Sporting Valverde',
            'FC Valverde',
            'AC Valverde',
            'Valverde Calcio',
            'Valverde United',
            'Polisportiva Valverde',
            'US Valverde',

            'Atletico Monteverde',
            'Real Monteverde',
            'Virtus Monteverde',
            'Sporting Monteverde',
            'FC Monteverde',
            'AC Monteverde',
            'Monteverde Calcio',
            'Monteverde United',
            'Polisportiva Monteverde',
            'US Monteverde',

            'Atletico Porto',
            'Real Porto',
            'Virtus Porto',
            'Sporting Porto',
            'FC Porto Nuovo',
            'AC Porto',
            'Porto Calcio',
            'Porto United',
            'Polisportiva Porto',
            'US Porto',

            'Atletico Marina',
            'Real Marina',
            'Virtus Marina',
            'Sporting Marina',
            'FC Marina',
            'AC Marina',
            'Marina Calcio',
            'Marina United',
            'Polisportiva Marina',
            'US Marina',

            'Atletico Stella',
            'Real Stella',
            'Virtus Stella',
            'Sporting Stella',
            'FC Stella',
            'AC Stella',
            'Stella Calcio',
            'Stella United',
            'Polisportiva Stella',
            'US Stella',

            'Atletico Europa',
            'Real Europa',
            'Virtus Europa',
            'Sporting Europa',
            'FC Europa',
            'AC Europa',
            'Europa Calcio',
            'Europa United',
            'Polisportiva Europa',
            'US Europa',

            'Atletico Primavera',
            'Real Primavera',
            'Virtus Primavera',
            'Sporting Primavera',
            'FC Primavera',
            'AC Primavera',
            'Primavera Calcio',
            'Primavera United',
            'Polisportiva Primavera',
            'US Primavera',

            'Atletico Olimpica',
            'Real Olimpica',
            'Virtus Olimpica',
            'Sporting Olimpica',
            'FC Olimpica',
            'AC Olimpica',
            'Olimpica Calcio',
            'Olimpica United',
            'Polisportiva Olimpica',
            'US Olimpica',

            'Atletico Borgo',
            'Real Borgo',
            'Virtus Borgo',
            'Sporting Borgo',
            'FC Borgo',
            'AC Borgo',
            'Borgo Calcio',
            'Borgo United',
            'Polisportiva Borgo',
            'US Borgo',

            'Atletico Centro',
            'Real Centro',
            'Virtus Centro',
            'Sporting Centro',
            'FC Centro',
            'AC Centro',
            'Centro Calcio',
            'Centro United',
            'Polisportiva Centro',
            'US Centro',

            'Atletico Nord',
            'Real Nord',
            'Virtus Nord',
            'Sporting Nord',
            'FC Nord',
            'AC Nord',
            'Nord Calcio',
            'Nord United',
            'Polisportiva Nord',
            'US Nord',

            'Atletico Sud',
            'Real Sud',
            'Virtus Sud',
            'Sporting Sud',
            'FC Sud',
            'AC Sud',
            'Sud Calcio',
            'Sud United',
            'Polisportiva Sud',
            'US Sud',

            'Atletico Est',
            'Real Est',
            'Virtus Est',
            'Sporting Est',
            'FC Est',
            'AC Est',
            'Est Calcio',
            'Est United',
            'Polisportiva Est',
            'US Est',

            'Atletico Ovest',
            'Real Ovest',
            'Virtus Ovest',
            'Sporting Ovest',
            'FC Ovest',
            'AC Ovest',
            'Ovest Calcio',
            'Ovest United',
            'Polisportiva Ovest',
            'US Ovest',

            'Atletico Verde',
            'Real Verde',
            'Virtus Verde',
            'Sporting Verde',
            'FC Verde',
            'AC Verde',
            'Verde Calcio',
            'Verde United',
            'Polisportiva Verde',
            'US Verde',

            'Atletico Azzurra',
            'Real Azzurra',
            'Virtus Azzurra',
            'Sporting Azzurra',
            'FC Azzurra',
            'AC Azzurra',
            'Azzurra Calcio',
            'Azzurra United',
            'Polisportiva Azzurra',
            'US Azzurra',

            'Atletico Phoenix',
            'Real Phoenix',
            'Virtus Phoenix',
            'Sporting Phoenix',
            'FC Phoenix',
            'Phoenix United',
            'Phoenix Calcio',
            'Polisportiva Phoenix',
            'US Phoenix',
            'Phoenix 2000',
        ];
    }

    public static function randomFullName(): string
    {
        $firstNames = self::firstNames();
        $lastNames = self::lastNames();

        return $firstNames[array_rand($firstNames)] . ' ' . $lastNames[array_rand($lastNames)];
    }

    public static function randomTeamName(): string
    {
        $names = self::teamNames();

        return $names[array_rand($names)];
    }
}
